### ISSUE TITLE
Ortho Profile for the Lexibank Revision

### ISSUE THREAD

**Issue by LinguList** [lexibank/tolmiebritishcolumbia#2]
@chrzyki, do you think we can start with a draft profile? I'd assist when I have time. We could go language-specific as well.

**Comment by chrzyki** [comment]
Yes! I'd like to - I'll gather what I have here. And I'd strongly opt for a language-specific profile as the languages reported  here have very individual requirements.

**Comment by LinguList** [comment]
So the procedure for this case is now as shown in my forthcoming blog 
post here:

https://calc.hypotheses.org/files/2021/08/calcip-04-09-011.pdf

First a profile that passes everything (no matter how badly), then use 
the simple script (which I'd opt to add to pylexibank as well, since it 
is so useful). See lexibank/sidwellvietic/raw/orthography.py

**Comment by chrzyki** [comment]
Great, thanks, I'll check this out!

**Comment by chrzyki** [comment]
Closed in favour of #3.
